# -*- coding: utf-8 -*-
"""Clean.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e4_FbghvzgpDnyHG7wIPM8cAg-EiiufL
"""

import pandas as pd

df=pd.read_csv("/content/bristol-air-quality-data.csv",sep=';',engine='python')

df

UniqueSite=df['SiteID'].unique()
UniqueSite   #15
UniqueSite[0]
for site in UniqueSite:
  print(site)

UniqueLocation=df['Location'].unique()
for location in UniqueLocation:
  print(location)

df = df[df['SiteID'].notna()]
df['SiteID'].unique()