# -*- coding: utf-8 -*-
"""Crop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wegc_1uUyaSzZK_P7jxl7wzSgT1hIvkR
"""

import pandas as pd

df=pd.read_csv("/content/bristol-air-quality-data.csv",sep=';',engine='python')

df

df['Date Time'] = pd.to_datetime(df['Date Time'], format="%Y-%m-%d %H:%M")
df

df = df.loc[(df['Date Time'] >= '2010-01-01')]
df