-- MySQL Script generated by MySQL Workbench
-- Fri Jan 14 11:09:03 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`partical pollution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`partical pollution` ;

CREATE TABLE IF NOT EXISTS `mydb`.`partical pollution` (
  `Nox` INT NULL,
  `No2` INT NULL,
  `No` INT NULL,
  `ID_NO` INT NOT NULL,
  PRIMARY KEY (`ID_NO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Volitle particular matter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Volitle particular matter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Volitle particular matter` (
  `VPM10` INT NULL,
  `VPM2.5` VARCHAR(45) NULL,
  `ID_VPM` INT NULL,
  CONSTRAINT `ID_VPM`
    FOREIGN KEY ()
    REFERENCES `mydb`.`partical pollution` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oxides`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`oxides` ;

CREATE TABLE IF NOT EXISTS `mydb`.`oxides` (
  `ID_O` INT NOT NULL,
  `CO` VARCHAR(45) NULL,
  `CO3` VARCHAR(45) NULL,
  `SO2` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_O`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Non Volitile Particular Matter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Non Volitile Particular Matter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Non Volitile Particular Matter` (
  `ID_NVMP` INT NOT NULL,
  `NVMP10` VARCHAR(45) NULL,
  `NVMP2.5` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_NVMP`),
  CONSTRAINT `ID_MVMP`
    FOREIGN KEY ()
    REFERENCES `mydb`.`oxides` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`particular matter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`particular matter` ;

CREATE TABLE IF NOT EXISTS `mydb`.`particular matter` (
  `ID_PM` INT NOT NULL,
  `PM10` VARCHAR(45) NULL,
  `MP2.5` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_PM`),
  CONSTRAINT `ID_PM`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Volitle particular matter` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ID_PM`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Non Volitile Particular Matter` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`environment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`environment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`environment` (
  `Temperature` INT NULL,
  `Air Pressure` VARCHAR(45) NULL,
  `Relative Humudity` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Location` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `SiteID` INT NOT NULL,
  `Location` VARCHAR(45) NULL,
  `geo_points` VARCHAR(45) NULL,
  PRIMARY KEY (`SiteID`),
  CONSTRAINT `SiteID`
    FOREIGN KEY ()
    REFERENCES `mydb`.`environment` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Date` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Date` (
  `DateStart` INT NOT NULL,
  `DateEnd` VARCHAR(45) NULL,
  `Current` VARCHAR(45) NULL,
  PRIMARY KEY (`DateStart`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Instrument`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Instrument` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Instrument` (
  `Intrumentid` INT NOT NULL,
  `Intrumenttype` VARCHAR(45) NULL,
  PRIMARY KEY (`Intrumentid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
